# Generated by Django 5.2.1 on 2025-06-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroTareas',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('descripcion', models.CharField(blank=True, max_length=400)),
                ('estado', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
