# Generated by Django 5.2.1 on 2025-06-03 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudtareas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaTareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigo_tarea', to='crudtareas.registrotareas')),
                ('descripcion_tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descripcion_tarea', to='crudtareas.registrotareas')),
                ('estado_tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado_tarea', to='crudtareas.registrotareas')),
                ('nombre_tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nombre_tarea', to='crudtareas.registrotareas')),
            ],
        ),
    ]
