# Generated by Django 5.2.1 on 2025-06-03 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudtareas', '0002_listatareas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualizacionTareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_actualizado', models.IntegerField(blank=True, default=0)),
                ('nombre_actualizado', models.CharField(blank=True, max_length=200)),
                ('descripcion_actualizado', models.CharField(blank=True, max_length=400)),
                ('estado_actualizado', models.CharField(blank=True, max_length=30)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actualizaciones', to='crudtareas.registrotareas')),
            ],
        ),
    ]
