# Generated by Django 5.2.1 on 2025-05-10 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GestionReportes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incluir_stock', models.BooleanField(default=True)),
                ('incluir_movimientos', models.BooleanField(default=True)),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionReportes.informe')),
            ],
        ),
    ]
