# Generated by Django 5.2.1 on 2025-05-12 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionProductos', '0005_alter_stock_umbral_minimo'),
        ('Registros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientostock',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionProductos.producto'),
        ),
    ]
