# Generated by Django 5.2.1 on 2025-05-15 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionProductos', '0005_alter_stock_umbral_minimo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
