# Generated by Django 5.2 on 2025-05-04 17:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0004_devolucion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('ubicacion', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InventarioObsoletos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Descontinuado', 'Descontinuado'), ('Obsoleto', 'Obsoleto')], max_length=20)),
                ('fecha_marcado', models.DateTimeField(default=django.utils.timezone.now)),
                ('revertido', models.BooleanField(default=False)),
                ('fecha_revertido', models.DateTimeField(blank=True, null=True)),
                ('marcado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obsoletos', to='AppInventario.producto')),
            ],
            options={
                'ordering': ['-fecha_marcado'],
            },
        ),
        migrations.CreateModel(
            name='TransferenciaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveBigIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('confirmada', models.BooleanField(default=False)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_destino', to='AppInventario.almacen')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_origen', to='AppInventario.almacen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppInventario.producto')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
