# Generated by Django 5.2.1 on 2025-05-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroTareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(blank=True, default=0)),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('descripcion', models.CharField(blank=True, max_length=400)),
            ],
        ),
    ]
