# Generated by Django 5.2.1 on 2025-05-23 16:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudtareas', '0004_eliminartareas'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualizaciontareas',
            name='codigo_actualizado',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='actualizaciontareas',
            name='estado_actualizado',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='actualizaciontareas',
            name='fecha_actualizacion',
            field=models.DateField(auto_now_add=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eliminartareas',
            name='motivo',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='listatareas',
            name='estado_tarea',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='estado_tarea', to='crudtareas.registrotareas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrotareas',
            name='estado',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='registrotareas',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
